server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  mustache:
    cache: false
    charset: UTF-8
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379